### ISSUE TITLE
Focusing Slack blurs the whole screen

### ISSUE THREAD

**Issue by ubuntudroid** [FelixKratz/dotfiles#10]
So this is a weird one:

I'm using the yabai/sketchybar parts of your dotfiles and overall they work live a charm and just look lovely.

However, when focusing Slack, the whole workspace is blurred. Happens 100% of the time. I can unblur the screen by simply focusing another app, but when I focus the Slack window again, blurring also happens again.

Switching workspaces doesn't fix the issue.

Please ignore the violet border on the screenshot—it is caused by yabai's border for the screenshot tool.

![CleanShot 2023-01-05 at 17 46 33](https://user-images.githubusercontent.com/519867/210834739-0af781d8-8190-4ba8-8bf2-417fb0620e05.png)

**Comment by FelixKratz** [comment]
Uhh thats weird, I think it is a problem with yabai: https://github.com/koekeishiya/yabai/issues/1471 and the border background blur. 

This will fix it:
```bash
yabai -m config window_border_blur off
```

**Comment by ubuntudroid** [comment]
You are right, that did the trick! 🎉  Many thanks for the quick help! 🤗
