### ISSUE TITLE
Xcode icon doesn't show

### ISSUE THREAD

**Issue by ubuntudroid** [FelixKratz/dotfiles#11]
![CleanShot 2023-01-05 at 18 13 35](https://user-images.githubusercontent.com/519867/210840845-eebaefb0-e924-4170-8fe3-17b69b1bc10e.png)

For some reason, the Xcode icon doesn't show up in the status bar. It looks to be properly configured in the mappings file, so I'm not sure what's wrong here. 🤷 Other icons seem to work fine so far.

**Comment by ubuntudroid** [comment]
yabai query for the screen:

```
$ yabai -m query --windows --space $space | jq -r ".[].app"
Warp
Code
Xcode
Code
```

**Comment by FelixKratz** [comment]
This must be a problem with the app icon font: https://github.com/kvndrsslr/sketchybar-app-font maybe you can report it there, I am not an expert on fonts myself but I can confirm that the Xcode icon indeed seems to be missing.

**Comment by ubuntudroid** [comment]
Right, that makes sense. Will report it over there! 🙌
