### ISSUE TITLE
No switching workspaces.

### ISSUE THREAD

**Issue by dhr-uvin** [FelixKratz/dotfiles#12]
Hello. 
I am using the sketchybar from the creator's dotfiles , I have installed sketchybar-app-font and the hack nerd font. However , sketchybar still doesn't show icons. It just hows the workspace numbers. How can I make it show icons?

Also , is it possible to switch workspaces? When i click one nothing happens.

**Comment by FelixKratz** [comment]
You can freely configure the click_script of the space indicators. I am using yabai scripting addition for this.
