### ISSUE TITLE
shkd keybinds seem to be wrong

### ISSUE THREAD

**Issue by ZirixCZ** [FelixKratz/dotfiles#14]
https://github.com/FelixKratz/dotfiles/blob/master/.config/skhd/skhdrc

For instance `shift + lalt - 1 ` is impossible, as when you press shift, you make `!` from 1. I think specific key code should be there instead. Cheers.

**Comment by FelixKratz** [comment]
I use this key combo every day. Works perfectly fine

**Comment by ZirixCZ** [comment]
Nevermind, my bad
