### ISSUE TITLE
Cannot focus space due to an error with the scripting-addition

### ISSUE THREAD

**Issue by braun-steven** [FelixKratz/dotfiles#15]
I've just switched from `koekeishiya/yabai` to your fork. It seems that the scripting-additions don't work though. I've uninstalled yabai and installed your fork with

```sh
brew tap FelixKratz/formulae
brew install --HEAD felixkratz/formulae/fyabai
```

I've put the following in `yabairc`

```sh
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &
sudo yabai --load-sa
```

and ran

```sh
echo "Add sudoer manually:\n '$(whoami) ALL = (root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | awk "{print \$1;}") $(which yabai) --load-sa' to '/private/etc/sudoers.d/yabai'"
```

to update `/private/etc/sudoers.d/yabai` accordingly. Then restarted the system just to be safe.

Running a space focus change results in:

```
$ yabai -m space --focus 3
cannot focus space due to an error with the scripting-addition.
```

Do you have any idea where I can start debugging?

Relevant files

- [yabairc](https://github.com/braun-steven/dotfiles/blob/master/configs/yabai/.config/yabai/yabairc)

Edit:
- I just reverted to `koekeishiya/yabai` and repeated the above steps and the space focus change works (no scripting additions error). Do I need to do something specific for your fork to make the scripting additions work?

**Comment by FelixKratz** [comment]
Try: `sudo yabai --uninstall-sa` before uninstalling yabai and installing fyabai

**Comment by braun-steven** [comment]
This resolved the issue, thanks!
