### ISSUE TITLE
`spaces.sh` causes loosing responsiveness in trackpad

### ISSUE THREAD

**Issue by andynameistaken** [FelixKratz/dotfiles#16]
- I am not sure if it's an issue that is solvable or if it's in the nature of the project, but when you leave `sketchybar` with `spaces.sh` sourced it causes too loose smoothnes of changing workspaces when using trackpad:

https://user-images.githubusercontent.com/15692002/229287993-f7964c3a-d2b8-49bb-a8da-0c5495569927.mov

- with commented out `spaces.sh`:

https://user-images.githubusercontent.com/15692002/229288153-a6fe0a79-260f-49c4-9b5c-56306664bd13.mov

**Comment by FelixKratz** [comment]
I think this is the same as: https://github.com/FelixKratz/SketchyBar/issues/220

It is basically a limitation of the window server with sticky windows.

The solution is to set
```bash
sketchybar --bar sticky=off
```

The sticky bar should only be used with disabled space switching animations.
