### ISSUE TITLE
Inquiry about the font used in icons.sh

### ISSUE THREAD

**Issue by 10ve** [FelixKratz/dotfiles#17]
I'm using the sketchybar config, but I'm having trouble with the symbols not displaying correctly in VS Code. I'm wondering if this is related to the font used in icons.sh.

Could you please provide some information about the font used in icons.sh

I appreciate your help in this matter.

Thank you!

<img width="374" alt="Screenshot 2023-04-12 at 10 15 05 AM" src="https://user-images.githubusercontent.com/11514850/231330231-14de28c8-d991-4d6d-aa15-cdfe2d4d2100.png">
<img width="444" alt="Screenshot 2023-04-12 at 10 15 30 AM" src="https://user-images.githubusercontent.com/11514850/231330291-ff3d0205-79c6-43ac-95af-62034998ee17.png">

**Comment by 10ve** [comment]
Thank you for your response.
I have found that using the 'SF Pro *' font family can help display symbol fonts correctly in editors.
in nvim
<img width="314" alt="Screenshot 2023-04-13 at 9 15 50 AM" src="https://user-images.githubusercontent.com/11514850/231620367-18943440-78b4-43e4-be6d-c424ca641074.png">
in vscode
<img width="302" alt="Screenshot 2023-04-13 at 9 16 30 AM" src="https://user-images.githubusercontent.com/11514850/231620465-c5634388-3659-4db3-8f63-d7f9ae7afe0f.png">
And can this command `lalt - 1 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[1] ]] && yabai -m space --focus $SPACES[1]` be improved to switch desktops?"

**Comment by FelixKratz** [comment]
> And can this command lalt - 1 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[1] ]] && yabai -m space --focus $SPACES[1] be improved to switch desktops?"

Thanks for this snippet, it is much cleaner than what I had in my config: https://github.com/FelixKratz/dotfiles/commit/184d3ba9687a9638256a4d02be64d888ecd823fd
What exactly do you mean by switch desktops?

**Comment by 10ve** [comment]
Thank you for your message. I just wanted to let you know that English is not my native language, so while I can understand the meaning of your message, my ability to express myself in English may be limited.

` alt - 1 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[1] ]] && yabai -m space --focus $SPACES[1]`, it seems that this command provides more flexibility when switching between spaces compared to using a fixed set of four desktops.
