### ISSUE TITLE
Weird padding on bar when clicking with right click

### ISSUE THREAD

**Issue by emretepedev** [FelixKratz/dotfiles#18]
before clicking
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/70508617/232210065-c1ef6dfb-4e82-473d-aeb8-0e35f31b69d4.png">

after clicking
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/70508617/232210126-ab873b06-b65e-4f7e-80d5-9ec2d359a51e.png">

what's wrong?

**Comment by FelixKratz** [comment]
It would show you the icons of the active applications if you have yabai running and the yabai events set up properly like this:
<img width="1512" alt="Screenshot 2023-04-15 at 13 12 16" src="https://user-images.githubusercontent.com/22680421/232210533-bb87d7c9-6996-46d9-870c-b7e219058e7e.png">

If you don't use this feature simply remove the yabai and its events here:
https://github.com/FelixKratz/dotfiles/blob/184d3ba9687a9638256a4d02be64d888ecd823fd/.config/sketchybar/items/front_app.sh#L25-L32

**Comment by emretepedev** [comment]
thanks for help! yes, I use yabai but I don't want to see app icons like this. I simply remove yabai events for this from config 🙏🏻
