### ISSUE TITLE
Missing bar color change animation for yabai stack layout

### ISSUE THREAD

**Issue by bin101** [FelixKratz/dotfiles#19]
https://github.com/FelixKratz/dotfiles/blob/4dcd36c6b72be0f385af0a56b4e3aae31d2842ff/.config/sketchybar/plugins/yabai.sh#L14

**Comment by FelixKratz** [comment]
https://github.com/FelixKratz/dotfiles/commit/eed5b4f40e9e97dedd9be3f1c4f70cf535c9312d


https://user-images.githubusercontent.com/22680421/233682686-4f67eb62-0205-446a-8654-fade6715a893.mp4
