### ISSUE TITLE
Return from fullscreen, space_change not triggered

### ISSUE THREAD

**Issue by bin101** [FelixKratz/dotfiles#21]
After returning from a fullscreen window, i.e. after pressing f on a fullscreen youtube video or 
![image](https://user-images.githubusercontent.com/12427722/234536922-554e77f0-c297-4af1-9b55-cfe50333130f.png)
 on the window bar doesn't seem to trigger the `space_change` event.

**Comment by FelixKratz** [comment]
I think this is purely related to the yabai.sh script not being registered properly to the space_change event, I think I will register the windows_on_spaces function for space_change as well later today, so you can try with my later update. 

The space_change event us actually performed, as you can clearly see by the space indicators of space 5. If the space_change event would not work it would not create/destroy the indicator of space 5.

**Comment by qns7** [comment]
Hey,

I have a similar problem and solved it by attaching the following to my 'space_change_scripts' (which cycles spaces on the active display left/prev and right/next) which is bound to a skhd-hotkey:
`fullscreen=$(yabai -m query --spaces --space | jq '.["is-native-fullscreen"]')

if [ "$fullscreen" = "true" ]; then
  sleep 0.1
  sketchybar --update # --reload
fi`
It's pretty self-explanatory and works perfectly for me.
Further here is one of my 'space_change_scripts' in one direction for context:
`#!/bin/bash

spaspa=$(yabai -m query --spaces --space)

curdis=$(yabai -m query --displays --display | jq '.index')
curspa=$(echo "$spaspa" | jq '.index')

spaces=$(yabai -m query --spaces --display "$curdis")
allspa=$(echo "$spaces" | jq ".[].index")
lowspa=$(echo "$spaces" | jq ".[] | select(.index < $curspa) | .index")

if [ ! -z "$lowspa" ]
then
  set -- $lowspa
  yabai -m space --focus ${@: -1}
else
  set -- $allspa
  yabai -m space --focus ${@: -1}
fi

fullscreen=$(echo "$spaspa" | jq '.["is-native-fullscreen"]')

if [ "$fullscreen" = "true" ]; then
  sleep 0.1
  sketchybar --update # --reload
fi`
Best regards 
Q
