### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Cu3PO42** [FelixKratz/dotfiles#24]
Hi there!

I'd like to use part of your config as a starting point for mine, but I noticed you didn't specify any license. Technically that means all rights are reserved except those that you granted implicitly by agreeing to GitHub's TOS. Since you include installation instructions, I assume you meant for other people to be able to use your config. I'd love if you could specify a license so that everyone can know what exactly is allowed and what is not. I've found [https://choosealicense.com](https://choosealicense.com) to be a decent guide to different options.

Thanks so much!

**Comment by FelixKratz** [comment]
I have added a simple and permissive license, have fun modifying the config.
