### ISSUE TITLE
No battery icon and wifi icon not reflecting the wifi.

### ISSUE THREAD

**Issue by FormalSnake** [FelixKratz/dotfiles#25]
![Screenshot 2023-08-30 at 16 33 44](https://github.com/FelixKratz/dotfiles/assets/90651091/0759d38d-eb9e-4b9e-a13a-852b72c0ca42)

Am I missing something?

I also cannot click the desktop thingies and the notification tray says it has something but it is empty

**Comment by FormalSnake** [comment]
unrelated question, but how do I make it have background blur and float?

**Comment by FormalSnake** [comment]
It does show my IP correctly

**Comment by FormalSnake** [comment]
How do I fix that?

**Comment by FelixKratz** [comment]
> How do I fix that?

Just above the `ICON=...` line I have reference above put:
```bash
INFO="$(/System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport -I  | awk -F' SSID: '  '/ SSID: / {print $2}')"
```

If this does not fix it I am not sure

**Comment by FelixKratz** [comment]
Try running this command in your commandline while the bar is running:
```bash
sketchybar --bar color.alpha=0.5 corner_radius=11 blur_radius=20 y_offset=10 margin=10
```
You can play with the values until you like it.
