### ISSUE TITLE
SketchyBar Icons not appearing

### ISSUE THREAD

**Issue by iCraft85** [FelixKratz/dotfiles#26]
So I installed the sketchybar-app-fonts but the icons still don't seem to be appearing, I am not rly sure what is wrong with it.
Is there some other fonts I need to install or smth?

<img width="1512" alt="Screenshot 2023-09-02 at 1 10 13 PM" src="https://github.com/FelixKratz/dotfiles/assets/58494292/b66a1bd1-9387-4625-831b-658f02218eeb">

**Comment by FelixKratz** [comment]
You need to install sf-symbols and the other required tool as well (see the readme):
```bash

brew install --cask sf-symbols
brew install jq
brew install gh
brew install switchaudio-osx
curl -L https://github.com/kvndrsslr/sketchybar-app-font/releases/download/v1.0.4/sketchybar-app-font.ttf -o $HOME/Library/Fonts/sketchybar-app-font.ttf
```

**Comment by iCraft85** [comment]
I have run all the commands but the issue seems to still persist.

**Comment by FelixKratz** [comment]
If you run the Font Book application, are you able to find SF font families such as SF Pro?

**Comment by iCraft85** [comment]
No, it doesn't seem to appear in font book
