### ISSUE TITLE
Windows blurred?

### ISSUE THREAD

**Issue by Sasutski** [FelixKratz/dotfiles#28]
Blurring occurs right after I ran the .install.sh
![WhatsApp Image 2023-09-14 at 16 53 15](https://github.com/FelixKratz/dotfiles/assets/122426751/9de9bee0-440c-46b9-8feb-28d1cb0894b0)
I am using a M1 chip Macbook.
I don't really know if this is a problem of me not understanding how to run the code properly, my mac having contradicting code or something, or really an issue.
Either way, can someone figure what is happening?
I had to reset my macbook for this :(

**Comment by FelixKratz** [comment]
This is something yabai does due to a problem on Ventura I think, you have to disable the window blur in yabai:
```bash
yabai -m window_border_blur off
```
but this is the setting I am using already in my config...

**Comment by Sasutski** [comment]
Ah. I got it to work already, didnt understand what was being installed.\

I do have one question though.

How do I make the battery icon and spotify bar always show even when battery is full and spotify is not playing

Im trying to play around with it.

does it have something to do with the plugin battery.sh?

BATTERY_INFO="$(pmset -g batt)"
PERCENTAGE=$(echo "$BATTERY_INFO" | grep -Eo "\d+%" | cut -d% -f1)
CHARGING=$(echo "$BATTERY_INFO" | grep 'AC Power')

if [ $PERCENTAGE = "" ]; then
  exit 0
fi

DRAWING=on
COLOR=$WHITE
case ${PERCENTAGE} in
  9[0-9]|100) ICON=$BATTERY_100; DRAWING=off
  ;;
  [6-8][0-9]) ICON=$BATTERY_75; DRAWING=off
  ;;
  [3-5][0-9]) ICON=$BATTERY_50
  ;;
  [1-2][0-9]) ICON=$BATTERY_25; COLOR=$ORANGE
  ;;
  *) ICON=$BATTERY_0; COLOR=$RED
esac

if [[ $CHARGING != "" ]]; then
  ICON=$BATTERY_CHARGING
  DRAWING=off
fi

sketchybar --set $NAME drawing=$DRAWING icon="$ICON" icon.color=$COLOR
