### ISSUE TITLE
[sketchybar] `brew services start sketchybar` without any effect when click the `volume` or `timezome` and so on

### ISSUE THREAD

**Issue by Guang1234567** [FelixKratz/dotfiles#29]
Hello dev:

`brew services start sketchybar` without any effect when click the `volume` or `timezome` and so on.

![image](https://github.com/FelixKratz/dotfiles/assets/8240718/73f0bae4-2d71-4eff-ae54-6dcf1ae5c225)

But just launch `sketchybar` in the command-line, everting is ok when click on some sketchybar widgets.

![image](https://github.com/FelixKratz/dotfiles/assets/8240718/b3db0679-4990-4747-b185-745d65baf00f)

![image](https://github.com/FelixKratz/dotfiles/assets/8240718/988b2d72-9876-466f-9ff6-e6bc3ab254f9)

Could you give me some suggest, thanks.

**Comment by FelixKratz** [comment]
Which macOS version are you using?

**Comment by Guang1234567** [comment]
> Which macOS version are you using?

macos 12.7

![](https://github.com/FelixKratz/dotfiles/assets/8240718/10792501-e89f-44c6-bc6e-198be23278e0)

**Comment by FelixKratz** [comment]
Are you using the latest sketchybar version?

**Comment by Guang1234567** [comment]
> Are you using the latest sketchybar version?

@FelixKratz 

https://github.com/FelixKratz/SketchyBar/releases/tag/v2.17.1

stll not working, hahaha, thanks.

**Comment by Guang1234567** [comment]
BTW, where is the below theme if you known?   thanks

![image](https://github.com/FelixKratz/dotfiles/assets/8240718/d7579533-b02f-4c79-952b-db73b5cc95bf)

**Comment by FelixKratz** [comment]
Maybe try upgrading to a newer macOS version. I can not debug Monterey and it seems to work on Big Sur

**Comment by Guang1234567** [comment]
> Maybe try upgrading to a newer macOS version. I can not debug Monterey and it seems to work on Big Sur

ok,  thanks.
