### ISSUE TITLE
space bar not update when exec "yabai -m space 2 --swap 3"

### ISSUE THREAD

**Issue by jheroy** [FelixKratz/dotfiles#3]
space create, space focus works fine, but not space swap.

**Comment by FelixKratz** [comment]
On lastest sketchybar master https://github.com/FelixKratz/SketchyBar/commit/f6bc244bc117641ddd377c4e5c31dcfec2d1cd92 you can do it like this (will be included in the next release v2.9.1):
```bash
yabai -m space 2 --swap 3 && sketchybar --trigger space_change
```

This is needed because there is no actual space change event emitted when yabai switches the spaces.
