### ISSUE TITLE
Memory leak or increasing buffer in cpu.h

### ISSUE THREAD

**Issue by gallantcrusader** [FelixKratz/dotfiles#32]
might be due to underlying mach implementation in sketchybar.h, but increases by 4kb(?) every update

**Comment by FelixKratz** [comment]
Are you using lastest commit?

**Comment by gallantcrusader** [comment]
Nope, sorry, please update the header in SketchyBarHelper I think they may be different, thanks!

**Comment by FelixKratz** [comment]
Thanks for the heads up, it should be fixed with this commit: https://github.com/FelixKratz/SketchyBarHelper/commit/bf4ff7487df295727cb1256ae92cdc257f506948
can you confirm?

**Comment by gallantcrusader** [comment]
Looks good, please remove the `static inline` from the methods: event_server_begin, env_get_value_for_key, and sketchybar because I am using Rust bindings so those methods need to be externally available please. Also I changed the int on line 210 to uint32_t to make the comparisons the same type.
