### ISSUE TITLE
Payload (0x0) error

### ISSUE THREAD

**Issue by Kana-fi** [FelixKratz/dotfiles#35]
Every time when I restart fyabai or my mac, I keep receiving the error below. How do I fix it?
![Screenshot 2023-12-23 at 3 03 55 PM](https://github.com/FelixKratz/dotfiles/assets/106124331/23f0160f-1e72-473c-a226-c132e5e62867)

**Comment by FelixKratz** [comment]
Maybe try reinstall fyabai from head, I did some changes recently.

**Comment by Kana-fi** [comment]
> Maybe try reinstall fyabai from head, I did some changes recently.

I installed it yesterday or a day before, so what could that me?

**Comment by FelixKratz** [comment]
Try
```bash
sudo yabai --uninstall-sa
brew uninstall fyabai
brew install fyabai --head
sudo yabai --load-sa
yabai
```

**Comment by Kana-fi** [comment]
> Did some changes today that probably fix this. Try
> 
> ```shell
> sudo yabai --uninstall-sa
> brew uninstall fyabai
> brew install fyabai --head
> sudo yabai --load-sa
> yabai
> ```

brew install fyabai --head
sudo yabai --load-sa
yabai
==> Fetching felixkratz/formulae/fyabai
==> Cloning https://github.com/FelixKratz/yabai.git
Updating /Users/maksymdemydok/Library/Caches/Homebrew/fyabai--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 74c3a7e document changes
==> Installing fyabai from felixkratz/formulae
==> make -j1 install
==> codesign --force -s - /private/tmp/fyabai-20231223-10041-fef2cz/bin/yabai
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink bin/yabai
Target /opt/homebrew/bin/yabai
is a symlink belonging to yabai. You can unlink it:
  brew unlink yabai

To force the link and overwrite all conflicting files:
  brew link --overwrite fyabai

To list all files that would be deleted:
  brew link --overwrite --dry-run fyabai

Possible conflicting files are:
/opt/homebrew/bin/yabai -> /opt/homebrew/Cellar/yabai/6.0.1/bin/yabai
==> Caveats
To restart felixkratz/formulae/fyabai after an upgrade:
  brew services restart felixkratz/formulae/fyabai
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/fyabai/bin/yabai
==> Summary
🍺  /opt/homebrew/Cellar/fyabai/HEAD-74c3a7e: 8 files, 1.7MB, built in 7 seconds
==> Running `brew cleanup fyabai`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
yabai: could not acquire lock-file! abort..
What to do with the error?

**Comment by Kana-fi** [comment]
> Did some changes today that probably fix this. Try
> 
> ```shell
> sudo yabai --uninstall-sa
> brew uninstall fyabai
> brew install fyabai --head
> sudo yabai --load-sa
> yabai
> ```

Sorry, nevermind, I guess it's okay now.

**Comment by Kana-fi** [comment]
Thank you for your help. 🤩
