### ISSUE TITLE
Sketchybar Persists in Fullscreen

### ISSUE THREAD

**Issue by landoncrabtree** [FelixKratz/dotfiles#37]
Hi there!

Firstly, thank you for your work with SketchyBar :) I'm using your sketchybarr dotfiles as a starting point for my configuration, but had a quick question regarding fullscreen. If I enter fullscreen (ie: YouTube video), the bar persists. Is there any way to hide it? I thought it might be a SketchyBar issue at first (ie https://github.com/FelixKratz/SketchyBar/issues/451) but tested the minimal configured bar

```
sketchybar --bar color=0xffffffff y_offset=50 height=10 topmost=on
```

and it disappeared in fullscreen. I'm guessing it's some option in this sketchybar configuration, but haven't been able to pinpoint where it is and was wondering if you could provide any advice.

I've tried
```
sticky=off
topmost=on
```

and other then that, I'm not sure what most of the other configured options mean.

**Comment by landoncrabtree** [comment]
And I know this isn't really an _issue_ with your dotfiles, since it's your personal preference. Just wasn't sure how else to reach out.

**Comment by FelixKratz** [comment]
Sorry, I think I have missed the notification of this issue. Could you try with sketchybar v2.20.1 and `sticky=on` again? It should hide in a native fullscreen application.
