### ISSUE TITLE
Config features not working

### ISSUE THREAD

**Issue by fabiohj7** [FelixKratz/dotfiles#38]
I saw the config and loved it. I copy the files and paste them into my computer. There are some errors that I tried fixing but found myself stuck and not able to fix them.
<img width="1440" alt="screenshot 2024-01-18 at 7 22 51 PM" src="https://github.com/FelixKratz/dotfiles/assets/64344356/f7c943ba-1779-418b-bec1-0ea09f6bd18d">
Everything seems to work fine but when clicking on the icons to the right nothing seems to happen.
The calendar seems to not display correctly.
The spaces are not interactive at all (Cannot click on them).
The only things that seem to be working correctly are the CPU usage and the apple logo.

I am using MacOS Ventura Version 13.6.1
Skethybar version: v2.19.6
yabai version: v6.0.1

**Comment by FelixKratz** [comment]
Maybe try the one line installer, it installs all dependencies:
```bash
curl -L https://raw.githubusercontent.com/FelixKratz/dotfiles/master/install_sketchybar.sh | sh
```

**Comment by fabiohj7** [comment]
That fixed it, thank you!
