### ISSUE TITLE
Change color of app icons

### ISSUE THREAD

**Issue by BennyOe** [FelixKratz/dotfiles#4]
Hi and first of all thank you for this amazing piece of software. I have to work with macOS as my company requires it and thanks to you and yabai I'm a little closer to my loved linux environment.

Is there any way to get change the color for the app icons that are displayed after every space number? I didn't manage to find these. 
![image](https://user-images.githubusercontent.com/45036971/202249306-b9b10410-b075-4bba-a226-cc87e1aee9da.png)

Thanks for the support and keep up the nice work!

**Comment by FelixKratz** [comment]
Those icons are stored in the `label` of the space, you can change the color via the `label.color` property of the spaces.
