### ISSUE TITLE
Unknown apps logo

### ISSUE THREAD

**Issue by fabiohj7** [FelixKratz/dotfiles#40]
I have been using a slightly modified version of your sketchybar set-up, in the spaces section I show the icon of the apps that I have opened, but I found that there are a lot of apps that do not have an icon. I was wondering if there is a way that I can add this icon or from where are this icons being pulled?
![screenshot 2024-01-31 at 12 23 35 AM](https://github.com/FelixKratz/dotfiles/assets/64344356/f3eb6763-79ac-4671-b930-a06a6484bdb1)

**Comment by FelixKratz** [comment]
Icons are from the excellent sketchybar-app-font: https://github.com/kvndrsslr/sketchybar-app-font/issues
