### ISSUE TITLE
CapsLock  Remapped

### ISSUE THREAD

**Issue by crates51** [FelixKratz/dotfiles#43]
Hello, i just ran the .install.sh script and it seems my capslock has been remapped to some wierd action, which i cant describe, all i know that i can exit tha mode which enter by pressing a, and i can move trough terminal.... with the cursur. anyhow, i used capslock in the past as escape key.

any idea what might happen?

Also, thanks for the dotfiles, everything else is great :D!

**Comment by crates51** [comment]
also, i saw that you added at the end:  

`echo "Do not forget to disable SIP and reconfigure keyboard -> $HOME/.config/keyboard..."
`
but i really didn't find that keyboard directory in the .config file..

**Comment by FelixKratz** [comment]
Maybe because of svim? To be honest, I didnt expect anyone to blindly run the entire install script. There are many things only required for my personal workflow:
```bash
brew services stop svim
```

**Comment by crates51** [comment]
Ohhh, right, that was it.

Thankss!!

Also. not really, blindly, i just moved to macOS from linux, and i had a pretty fresh start, so nothing to lose, and read the script.. some lines here some there :))

Also, i am not sure what you did with the mouse but now is more snappy, and the typing speed is so nice.
