### ISSUE TITLE
Can't create new space

### ISSUE THREAD

**Issue by chxlium** [FelixKratz/dotfiles#50]
Hey, I am new to this.
Install everything and it seems fine.
But it cannt create new space in the bar with mouse click.
Is it because the System Integrity Protection for yabai?

![IMG_9528](https://github.com/FelixKratz/dotfiles/assets/95418610/ea9e0636-5106-4a23-87fa-88a391b09218)

**Comment by chxlium** [comment]
never mind. I was dumb hahah

**Comment by h4ckd0tm3** [comment]
I'm still being dumb. Mind sharing ur insights? xD

**Comment by lcxrocks** [comment]
@chxlium +1. Still wondering how to create new spaces with mouse click in this lua version. Any ideas?

**Comment by FelixKratz** [comment]
I dont need it because I have a shortcut in my setup, but it is really easy to add such button.

**Comment by lcxrocks** [comment]
> I dont need it because I have a shortcut in my setup, but it is really easy to add such button.

Thank you! Knowing that this config doesn't include such feature is very helpful!
