### ISSUE TITLE
How to create new Space?

### ISSUE THREAD

**Issue by h4ckd0tm3** [FelixKratz/dotfiles#52]
Was already asked in #50 but closed without clarifying how to actually create a new space. 
Might just me being stupid but I really can't find it ^^'.

Thank you in advance!

**Comment by starboi-63** [comment]
Not sure if this helps, but I use `skhd` with the following keybinds for spaces:

```bash
## Navigation (lalt - ...)
# Create a new space: lalt + n
lalt - n : yabai -m space --create

# Move to previous/next space: lalt - {i, o}
lalt - i : yabai -m space --focus prev
lalt - o : yabai -m space --focus next

# Delete the current space: lalt + d
lalt - w : yabai -m space --destroy

# Space Navigation (four spaces per display): lalt - {1, 2, 3, 4}
lalt - 1 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[1] ]] && yabai -m space --focus $SPACES[1]
lalt - 2 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[2] ]] && yabai -m space --focus $SPACES[2]
lalt - 3 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[3] ]] && yabai -m space --focus $SPACES[3]
lalt - 4 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[4] ]] && yabai -m space --focus $SPACES[4]
```

So, `lalt + n` in this case would create a new space.

**Comment by h4ckd0tm3** [comment]
> Not sure if this helps, but I use `skhd` with the following keybinds for spaces:
> 
> ```shell
> ## Navigation (lalt - ...)
> # Create a new space: lalt + n
> lalt - n : yabai -m space --create
> 
> # Move to previous/next space: lalt - {i, o}
> lalt - i : yabai -m space --focus prev
> lalt - o : yabai -m space --focus next
> 
> # Delete the current space: lalt + w
> lalt - w : yabai -m space --destroy
> 
> # Space Navigation (four spaces per display): lalt - {1, 2, 3, 4}
> lalt - 1 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[1] ]] && yabai -m space --focus $SPACES[1]
> lalt - 2 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[2] ]] && yabai -m space --focus $SPACES[2]
> lalt - 3 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[3] ]] && yabai -m space --focus $SPACES[3]
> lalt - 4 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[4] ]] && yabai -m space --focus $SPACES[4]
> ```
> 
> So, `lalt + n` in this case would create a new space. But really, you should be able to click on the right arrow between the `spaces` and `front_app`:
> 
> <img alt="image" width="224" src="https://private-user-images.githubusercontent.com/44245692/337717929-8c9fa995-1ae0-4d94-95a9-8df8caaf917c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NDIzMTYsIm5iZiI6MTcxNzg0MjAxNiwicGF0aCI6Ii80NDI0NTY5Mi8zMzc3MTc5MjktOGM5ZmE5OTUtMWFlMC00ZDk0LTk1YTktOGRmOGNhYWY5MTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDEwMjAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMDc3ZmVhNjcwZjMwZTI1NzEzOWNlYzBkYTAwODcxNDBlNmVjZmU5NDU3YTRhMGM5MTE2YWUzZmQ2ZTc2YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7lxhgO2JZuyLr8ZG5HeT26vBbWQ91H9A-7B7fpNe82g">

Thanks for sharing! I am currently using the new Lua based config, which is missing the arrow and I could not find a replacement for that yet. Will probably use ur approach with the key bindings!

Thanks!

**Comment by starboi-63** [comment]
Of course!
