### ISSUE TITLE
Battery stopped working after reboot

### ISSUE THREAD

**Issue by noshitsherlock** [FelixKratz/dotfiles#55]
I am using your configuration, and after a reboot, the battery widget just stopped working. I have a new MacBook air 15 m3.

<img width="463" alt="image" src="https://github.com/FelixKratz/dotfiles/assets/3532879/735ccdb0-5b39-4c38-bdcd-6a82f3a3188f">

**Comment by DensityInfinite** [comment]
I find [this comment](https://github.com/FelixKratz/SbarLua/issues/29#issuecomment-2201709579) to be the simplest workaround. All *you* need to do is to replace the "xxxxxx" part with your username.

**Comment by FelixKratz** [comment]
I have updated SbarLua for the new version of the lua runtime https://github.com/FelixKratz/SbarLua/commit/ea95c2b5562d59a285b39d99075fc7571fe7b31a

**Comment by noshitsherlock** [comment]
Awesome! That worked 👌
