### ISSUE TITLE
Volume icon

### ISSUE THREAD

**Issue by Swepz** [FelixKratz/dotfiles#6]
Firstly, great dotfiles!
Secondly, I am having issues getting the alias for the volume icon, even though renamed to "Centre". 
The slider works just fine but the volume icon is just blank in the mean while.
Do you have any suggestions?

File: items/volume.sh

```
sketchybar --add alias "Control Center,Sound" right                      \
           --rename "Control Center,Sound" volume_alias                   \
           --set volume_alias icon.drawing=on                                      \
```

**Comment by FelixKratz** [comment]
What does: `sketchybar --query default_menu_items` return? It could be that screen capture permissions are not given.

**Comment by Swepz** [comment]
> 

```
sketchybar --query default_menu_items
[
	"Control Centre,NowPlaying",
	"TextInputMenuAgent,Item-0",
	"Karabiner-Menu,Item-0",
	"Hidden Bar,hiddenbar_separate",
	"OneDrive,Item-0",
	"Hidden Bar,hiddenbar_expandcollapse",
	"Hidden Bar,hiddenbar_terminate",
	"Control Centre,Bluetooth",
	"Control Centre,Battery",
	"Control Centre,WiFi",
	"Control Centre,BentoBox",
	"Control Centre,Clock",
	"Spotlight,Item-0"
]
```
<img width="606" alt="Screenshot 2022-11-30 at 09 36 44" src="https://user-images.githubusercontent.com/32343381/204748020-378df955-9879-4f92-b903-581ef97c217c.png">


Cannot see "Control Centre,Sound", am I missing something that should be given permission?

**Comment by FelixKratz** [comment]
Do you see a volume icon in the macOS menu bar? If the volume item is not present in the macOS menu bar it can not be aliased into sketchybar.

**Comment by Swepz** [comment]
> Do you see a volume icon in the macOS menu bar? If the volume item is not present in the macOS menu bar it can not be aliased into sketchybar.

Good catch, it's working now! 
No, only when changing the volume, if changing settings -> System Preferences -> Sound -> Check "Show Sound in menu bar" -> Select Always

<img width="671" alt="Screenshot 2022-11-30 at 09 52 15" src="https://user-images.githubusercontent.com/32343381/204751482-7905dac2-099d-49ce-b2b5-8e0960491c05.png">
