### ISSUE TITLE
icons not showing

### ISSUE THREAD

**Issue by kasuke5** [FelixKratz/dotfiles#7]
I just switch to macos so sorry if it is a dumb question but I copy everythings, I got the good fonts 
- Hack Nerd
- SF Pro
- Font Awesome 6
- MesloLGL
- sketchybar-app-font
- sf-icons

I tried to tweak the bar with different fonts and icons but eveytime I either got nothing or a |?| icon
I don't know what to try (The volume icon is showing) 
I edit with visual studio and I can see icons there

**Comment by AjayShanker-geek** [comment]
To double confirm, you talking about sketchybar?

Refer to the official [website](https://felixkratz.github.io/SketchyBar/setup)

```
brew tap homebrew/cask-fonts
brew install --cask font-hack-nerd-font
```

**Comment by kasuke5** [comment]
Hello yes I'm talking about sketchybar, I already install this font like I mentionned 
I got Archlinux with i3 + polybar so I was like : this is the closest thing I can get :)
using Ventura btw if it change something

**Comment by kasuke5** [comment]
also is there a way to remove this windows things ?
<img width="532" alt="image" src="https://user-images.githubusercontent.com/10560045/205695095-c7de5f5d-db81-4fc2-aabd-5ba6b8c89a51.png">
it's not showing at launch but somehow it comes

**Comment by FelixKratz** [comment]
The icons on the right are all from sf-symbols:
```bash
brew install --cask sf-symbols
```

The space icons on the left are updated via the events that you must have pasted into your yabai/skhd configs (i.e. the icons for apps on spaces is generated by the event `windows_on_spaces`).
