### ISSUE TITLE
Icon for only Microsoft Teams and Outlook missing/hidden

### ISSUE THREAD

**Issue by zyrre** [FelixKratz/dotfiles#8]
Has anyone else experienced this? Icons for microsoft teams and outlook(outlook i just used :mail:) are not shown in the spaces preview. All other apps seem to work, including with spaces in name like Google Chrome.

You can tell that it is recognising that there is an app in that space, since the blank background is slightly wider than in a space where there are no apps, but no icon is showing up at all.

I am using felixkratz dotfiles with sketchybar-app-font.

Any idea what might cause it?

**Comment by FelixKratz** [comment]
I am not using those two applications myself but this should do it: 9a656514313ea9dd2d23021778772685ee987c10

**Comment by zyrre** [comment]
Oh, yeah I should have posted that. I got the latest app-font and I changed in icon_map to this:
```
"Microsoft Teams")
  icon_result=":microsoft_teams:"
  ;;
"Microsoft Outlook")
  icon_result=":mail:"
  ;;
```
I noticed my assumptions were incorrect about the size of the empty spaces though. It was just the right most space that always is a wider size when empty. If I put either of those apps in other spaces they appear identical to an empty space.

**Comment by FelixKratz** [comment]
The script that is responsible for generating the icons is here:
https://github.com/FelixKratz/dotfiles/blob/99c326c33b7f9503588ed5bd306f477e409c03ca/.config/sketchybar/plugins/yabai.sh#L41-L61

My suspicion would be that they might not be detected via yabai?
Try running:
```bash
yabai -m query --windows --space 1 | jq -r ".[].app"
```
when you have those two applications on the first space and see if they appear in the list of apps.

**Comment by zyrre** [comment]
Seems it was several things.
The microsoft teams .svg looks a bit odd, at leasts for me, in the app-font git. I changed to another icon and that worked, so maybe that icon is borked or im just failing at getting it to use the latest release.

For outlook you were correct, it is not detected by yabai.
